par_flows.par_flow.*:
  type: config_entity
  label: 'PAR Flow config'
  mapping:
    uuid:
      type: string
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    default_title:
      type: label
      label: 'Default title'
      nullable: true
    default_section_title:
      type: string
      label: 'Default section title'
      nullable: true
    description:
      type: string
      label: 'Description'
    save_method:
      type: string
      label: 'Save Method'
    states:
      type: sequence
      sequence:
        type: string
        label: 'States (route parameters) that the flow can vary by'
    steps:
      type: mapping
      label: "Steps"
      mapping:
        "route":
          type: text
          label: "Route"
        "form_id":
          type: text
          label: "Form ID"
          nullable: true
        "components":
          type: sequence
          label: "Components"
          nullable: true
          sequence:
            type: text
            label: "Component"
        "redirect":
          type: sequence
          label: "Redirects"
          nullable: true
          sequence:
            type: integer
            label: "Operation Redirect"
