par_partnership_application_flows.partnership_application_start:
  path: '/partnership/apply'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParSelectAuthorityForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParSelectAuthorityForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParSelectAuthorityForm::accessCallback'
par_partnership_application_flows.partnership_application_type:
  path: '/partnership/apply/type'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParApplicationTypeForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParApplicationTypeForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParApplicationTypeForm::accessCallback'
par_partnership_application_flows.partnership_application_authority_checklist:
  path: '/partnership/apply/checklist'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParChecklistForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParChecklistForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParChecklistForm::accessCallback'
par_partnership_application_flows.partnership_application_notify_existing:
  path: '/partnership/apply/notify-existing'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParNotifyExistingForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParNotifyExistingForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParNotifyExistingForm::accessCallback'
par_partnership_application_flows.partnership_application_partnership_about:
  path: '/partnership/apply/about'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParAboutPartnershipForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParAboutPartnershipForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParAboutPartnershipForm::accessCallback'
par_partnership_application_flows.partnership_application_organisation_name:
  path: '/partnership/apply/organisation/name'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParOrganisationNameForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParOrganisationNameForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParOrganisationNameForm::accessCallback'
par_partnership_application_flows.partnership_application_organisation_confirm:
  path: '/partnership/apply/organisation/confirm'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParOrganisationSuggestionForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParOrganisationSuggestionForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParOrganisationSuggestionForm::accessCallback'
par_partnership_application_flows.partnership_application_organisation_address:
  path: '/partnership/apply/organisation/address'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParAddressForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParAddressForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParAddressForm::accessCallback'
par_partnership_application_flows.partnership_application_organisation_contact:
  path: '/partnership/apply/organisation/contact'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParContactForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParContactForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParContactForm::accessCallback'
par_partnership_application_flows.partnership_application_review:
  path: '/partnership/apply/review'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParConfirmationReviewForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParConfirmationReviewForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParConfirmationReviewForm::accessCallback'
par_partnership_application_flows.partnership_application_invite:
  path: '/partnership/apply/{par_data_partnership}/invite/{par_data_person}'
  defaults:
    _form: '\Drupal\par_partnership_application_flows\Form\ParInviteForm'
    _title_callback: '\Drupal\par_partnership_application_flows\Form\ParInviteForm::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Form\ParInviteForm::accessCallback'
    par_data_partnership: \d+
    par_data_person: \d+
  options:
    parameters:
      par_data_partnership:
        type: entity:par_data_partnership
      par_data_person:
        type: entity:par_data_person
par_partnership_application_flows.partnership_application_invite_sent:
  path: '/partnership/apply/{par_data_partnership}/invite/sent/{par_data_person}'
  defaults:
    _controller: '\Drupal\par_partnership_application_flows\Controller\ParInviteSentController::content'
    _title_callback: '\Drupal\par_partnership_application_flows\Controller\ParInviteSentController::titleCallback'
  requirements:
    _permission: 'manage my authorities'
    _custom_access: '\Drupal\par_partnership_application_flows\Controller\ParInviteSentController::accessCallback'
    par_data_partnership: \d+
    par_data_person: \d+
  options:
    parameters:
      par_data_partnership:
        type: entity:par_data_partnership
      par_data_person:
        type: entity:par_data_person
