name: 'PAR Data Config'
description: 'The configuration required to correctly setup the PAR Data entities.'
type: module
core: 8.x
dependencies:
  - address
  - better_exposed_filters
  - comment
  - csv_serialization
  - datetime
  - datetime_range
  - field
  - file
  - file_entity
  - message
  - pagerer
  - par_data
  - par_data_config
  - rest
  - serialization
  - text
  - user
  - views
  - views_bulk_operations
  - views_data_export
package: PAR
